#
# Use changed_when and check_mode to
#  write a playbook that uses the shell
#  module without modifying the host.
#
- hosts: all
  tasks:
  - name: >
     Settin changed_when and check_mode after
     writing the command may be safer.
    shell: |
      pgrep -f oracle
    check_mode: no
    changed_when: no
