#
# Initialize innodb cluster
#
- name: Get my.cnf options
  command:
    grep ^group_replication /etc/my.cnf
  register: has_group_replication
  changed_when: false

- name: Create directory
  when: has_group_replication.rc == 1
  shell: |
    rm /var/lib/mysql/*  -fr

- name: Initialize datadir
  when: has_group_replication.rc == 1
  command: |
    mysqld --initialize --user=mysql

- name: Eventually start mysql
  command: pgrep -fa mysqld.*--
  register: mysqld_status
  changed_when: false
  failed_when: false

- name: First boot
  when: >-
    mysqld_status.rc != 0
  command: |
    mysqld --init-file=/code/ansible/initialize-replication.sql --user=mysql
  async: 300
  poll: 0
  register: mysqld_jid

- name: Wait for mysql
  wait_for:
    host: 0.0.0.0
    port: 3306
    delay: 1
    timeout: 20

- name: Prepare instance for clustering
  command: mysqlsh --js -f /code/ansible/check_cluster.py   --log-level=DEBUG4
  ignore_errors: true

- name: Take a nap
  pause: seconds=5

- name: Create cluster on local node
  run_once: yes
  delegate_to: db[0]
  shell: |-
    mysqlsh --uri icroot@{{ansible_default_ipv4.address}}:3306  --password=Secret%2017 --log-level=DEBUG4 <<EOF

    try {
        cluster = dba.createCluster('prod');
    } catch (err) {
        cluster = dba.getCluster('prod');
    }
    var options = {"password": "Secret%2017"};

    EOF

- name: Add instances to cluster
  delegate_to: db[0]
  when: >-
    ansible_hostname in db[1:]
  shell: |
    mysqlsh --uri icroot@localhost:3306  --password=Secret%2017 --log-level=DEBUG4 <<EOF
    try {
        cluster = dba.createCluster('prod');
    } catch(err) {
        cluster = dba.getCluster('prod');
    }
    var options = {"password": "Secret%2017"};
    cluster.addInstance('icroot@{{ansible_default_ipv4.address}}:3306', options);
    EOF

- name: Kill mysql
  command: pkill -f mysqld
