---
# This play includes another play
#

- hosts: web
  tasks:
  - name: install apache
    apt: name=apache2 state=latest

- import_playbook: web-1.yml
  when: >
    'missing' in groups

# always do it!
- import_playbook: web-1.yml
